services:
  # Combined Service for Free Tier
  - type: web
    name: gurukul-ai-combined-free
    env: python
    region: oregon
    plan: free
    buildCommand: cd Backend/combined_service && pip install -r requirements.txt
    startCommand: cd Backend/combined_service && python app.py
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/Backend
      - key: MONGODB_URI
        sync: false  # Use MongoDB Atlas free tier
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: HUGGINGFACE_API_TOKEN
        sync: false
      - key: AGENTOPS_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: CORS_ORIGINS
        value: "*"
      - key: USE_REDIS
        value: "false"
    healthCheckPath: /health
